// Client-side password-hash helpers.
//
// Adds two algorithms that don't fit the "one-shot digest" pattern of
// MD5/SHA/BLAKE (which live in hash-utils.js):
//   * bcrypt        — modern, standard adaptive hash. Uses bcryptjs.
//   * WordPress phpass — PortableHash / phpass format ($P$…) used by
//                     WordPress and older forks. Implemented inline
//                     against the WP source reference so no extra dep
//                     is needed.
//
// Both are non-deterministic (they embed a random salt in the hash
// string) and both encode their cost parameter so a single string is
// sufficient to verify a password later.

import bcrypt from 'bcryptjs';
import { md5 } from 'hash-wasm';

// ----- bcrypt --------------------------------------------------------------

/**
 * Compute a bcrypt hash of the given password.
 *
 * @param {string} password
 * @param {number} rounds Cost parameter (4-15 range makes sense; 10 is the
 *                        typical default). Each +1 doubles the work.
 * @returns {Promise<{hash: string, algorithm: 'bcrypt', rounds: number}>}
 */
export async function bcryptHash(password, rounds = 10) {
  const r = Math.max(4, Math.min(15, Number(rounds) || 10));
  const salt = await bcrypt.genSalt(r);
  const hash = await bcrypt.hash(password, salt);
  return { hash, algorithm: 'bcrypt', rounds: r };
}

/**
 * Verify a plaintext password against a bcrypt hash string.
 * @param {string} password
 * @param {string} hash
 * @returns {Promise<boolean>}
 */
export async function bcryptVerify(password, hash) {
  try { return await bcrypt.compare(password, hash); } catch { return false; }
}

// ----- WordPress phpass ----------------------------------------------------

// phpass base64 alphabet — NOT the standard one. Also used by crypt-blowfish
// legacy but WP's version uses this exact order.
const PHP_ITOA64 = './0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';

/**
 * Encode raw bytes using phpass's base64 variant.
 * Port of PasswordHash::encode64() from wp-includes/class-phpass.php.
 * @param {Uint8Array} input
 * @param {number} count number of bytes to encode
 * @returns {string}
 */
function encode64(input, count) {
  let output = '';
  let i = 0;
  while (i < count) {
    let value = input[i++];
    output += PHP_ITOA64[value & 0x3f];
    if (i < count) value |= input[i] << 8;
    output += PHP_ITOA64[(value >> 6) & 0x3f];
    if (i++ >= count) break;
    if (i < count) value |= input[i] << 16;
    output += PHP_ITOA64[(value >> 12) & 0x3f];
    if (i++ >= count) break;
    output += PHP_ITOA64[(value >> 18) & 0x3f];
  }
  return output;
}

/**
 * Convert a hex MD5 string (as returned by hash-wasm's md5) to a Uint8Array
 * of 16 raw bytes.
 */
function hexToBytes(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.substr(i * 2, 2), 16);
  }
  return out;
}

/**
 * Compute an MD5 digest of a concatenation of Uint8Arrays and return the
 * raw 16-byte digest.
 */
async function md5Bytes(...parts) {
  let total = 0;
  for (const p of parts) total += p.length;
  const buf = new Uint8Array(total);
  let off = 0;
  for (const p of parts) { buf.set(p, off); off += p.length; }
  const hex = await md5(buf);
  return hexToBytes(hex);
}

/**
 * Generate a random cryptographic salt (Uint8Array of the given length).
 */
function randomBytes(n) {
  const b = new Uint8Array(n);
  crypto.getRandomValues(b);
  return b;
}

/**
 * Compute a WordPress phpass Portable Hash of a password.
 *
 * @param {string} password
 * @param {number} iterationsLog2 The exponent portion of the cost
 *   parameter — WordPress uses 13 by default (=> 8192 iterations).
 *   Range 7..30. Higher = slower and more secure.
 * @param {string} prefix '$P$' (WordPress) or '$H$' (phpBB / generic
 *   phpass). Defaults to '$P$' to match WordPress users table.
 * @returns {Promise<{hash: string, algorithm: 'wp-phpass', iterations: number, prefix: string}>}
 */
export async function wpPhpassHash(password, iterationsLog2 = 13, prefix = '$P$') {
  const log2 = Math.max(7, Math.min(30, Number(iterationsLog2) || 13));
  const count = 1 << log2;
  // WordPress phpass uses an 8-character ASCII salt in the final hash
  // string. That 8-char string is generated by encoding 6 random bytes
  // with the phpass base64 alphabet, and it's the 8-char ASCII string
  // (not the raw 6 random bytes) that gets fed into MD5 as the salt.
  // See PasswordHash::crypt_private in wp-includes/class-phpass.php.
  const saltRandom = randomBytes(6);
  const saltStr = encode64(saltRandom, 6); // exactly 8 chars
  const saltBytes = new Uint8Array(saltStr.length);
  for (let i = 0; i < saltStr.length; i++) saltBytes[i] = saltStr.charCodeAt(i);
  // ASCII encode password so length behaviour matches PHP's byte-mode.
  const pwBytes = new TextEncoder().encode(password);
  // Iteration 0: md5(salt . password)
  let hash = await md5Bytes(saltBytes, pwBytes);
  // Then N more iterations: hash = md5(hash . password)
  for (let i = 0; i < count; i++) {
    hash = await md5Bytes(hash, pwBytes);
  }
  const output =
    prefix + PHP_ITOA64[log2] + saltStr + encode64(hash, 16);
  return { hash: output, algorithm: 'wp-phpass', iterations: count, prefix };
}

/**
 * Verify a plaintext password against a WordPress phpass hash string.
 * @param {string} password
 * @param {string} stored e.g. "$P$B<12 chars>..."
 * @returns {Promise<boolean>}
 */
export async function wpPhpassVerify(password, stored) {
  if (!stored || stored.length < 34) return false;
  const prefix = stored.substr(0, 3);
  if (prefix !== '$P$' && prefix !== '$H$') return false;
  const log2 = PHP_ITOA64.indexOf(stored[3]);
  if (log2 < 7 || log2 > 30) return false;
  // 8-char ASCII salt string, fed as raw bytes into MD5 (matches WP).
  const saltStr = stored.substr(4, 8);
  const saltBytes = new Uint8Array(8);
  for (let i = 0; i < 8; i++) saltBytes[i] = saltStr.charCodeAt(i);
  const count = 1 << log2;
  const pwBytes = new TextEncoder().encode(password);
  let hash = await md5Bytes(saltBytes, pwBytes);
  for (let i = 0; i < count; i++) hash = await md5Bytes(hash, pwBytes);
  const candidate = prefix + stored[3] + saltStr + encode64(hash, 16);
  // Constant-time compare
  if (candidate.length !== stored.length) return false;
  let diff = 0;
  for (let i = 0; i < candidate.length; i++) {
    diff |= candidate.charCodeAt(i) ^ stored.charCodeAt(i);
  }
  return diff === 0;
}

// ----- WordPress 6.8+ bcrypt ($wp$) ---------------------------------------
//
// From WordPress core (wp-includes/pluggable.php, wp_hash_password):
//
//   $password_to_hash = base64_encode(
//       hash_hmac( 'sha384', trim( $password ), 'wp-sha384', true )
//   );
//   return '$wp' . password_hash( $password_to_hash, PASSWORD_BCRYPT );
//
// So a stored WordPress 6.8+ hash looks like  "$wp$2y$10$...."  — a normal
// bcrypt hash with an extra "$wp" tag prepended. The pre-hash step is
// there to (a) work around bcrypt's 72-byte input limit for very long
// passwords and (b) provide domain separation via the fixed HMAC key
// "wp-sha384".

/**
 * Compute WordPress's HMAC-SHA-384 pre-hash of a password and return
 * the base64-encoded digest that will be fed into bcrypt.
 * @param {string} password
 * @returns {Promise<string>}
 */
async function wpPreHash(password) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    enc.encode('wp-sha384'),
    { name: 'HMAC', hash: 'SHA-384' },
    false,
    ['sign'],
  );
  const sig = await crypto.subtle.sign('HMAC', key, enc.encode(password.trim()));
  // Base64 encode the raw 48-byte digest to a standard base64 string.
  const bytes = new Uint8Array(sig);
  let bin = '';
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}

/**
 * Compute a WordPress 6.8+ ($wp$) password hash.
 * @param {string} password
 * @param {number} rounds bcrypt cost parameter (4..15). WordPress core
 *   uses 12 by default; we default to 12 here as well to match.
 * @returns {Promise<{hash: string, algorithm: 'wp-bcrypt', rounds: number}>}
 */
export async function wpBcryptHash(password, rounds = 12) {
  const r = Math.max(4, Math.min(15, Number(rounds) || 12));
  const prehashed = await wpPreHash(password);
  const salt = await bcrypt.genSalt(r);
  const bcryptHash = await bcrypt.hash(prehashed, salt);
  return { hash: '$wp' + bcryptHash, algorithm: 'wp-bcrypt', rounds: r };
}

/**
 * Verify a plaintext password against a WordPress 6.8+ ($wp$…) hash.
 * @param {string} password
 * @param {string} stored e.g. "$wp$2y$12$....."
 * @returns {Promise<boolean>}
 */
export async function wpBcryptVerify(password, stored) {
  if (!stored || !stored.startsWith('$wp$')) return false;
  const bcryptPart = stored.slice(3); // strip leading "$wp", leaves "$2y$..."
  if (!/^\$2[aby]\$/.test(bcryptPart)) return false;
  try {
    const prehashed = await wpPreHash(password);
    return await bcrypt.compare(prehashed, bcryptPart);
  } catch {
    return false;
  }
}
